version: '3'
services:
  app:
    image: ${DOCKER_USERNAME}/payments-platform:staging
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
